Fix: LeafletMap style error
The error `src/components/LeafletMap.tsx(111,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.` indicates a problem with how the `style jsx` is being used. This commit will correct the style definition within the LeafletMap component.